//Searching
export const SEARCHING_ITEMS = 'SEARCHING_ITEMS';
export const SEARCHING_ITEMS_SUCCESS = 'SEARCHING_ITEMS_SUCCCESS';
export const SEARCHING_ITEMS_ERROR = 'SEARCHING_ITEMS_ERROR';
//Detail
export const FETCHING_DETAIL_ITEM = 'FETCHING_DETAIL_ITEM';
export const FETCHING_DETAIL_ITEM_SUCCESS = 'FETCHING_DETAIL_ITEM_SUCCESS';
export const FETCHING_DETAIL_ITEM_ERROR = 'FETCHING_DETAIL_ITEM_ERROR';
